# This pre-builds wheels for xmlsec and grpcio into a Docker base image 
# because they seem to take a long time to compile.

name: Alpine base image with wheels

on:
  push:
    branches: [ main ]
    paths: 
    - 'alpine-wheels/**'
  schedule:
    # At 08:00 on day-of-month 1 (https://crontab.guru/#0_8_1_*_*)
    - cron: '0 8 1 * *'

jobs:

  alpine-with-wheels:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/@master
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      - name: Build xmlsec and grpcio
        run: |
          cd alpine-wheels
          project_id=$(gcloud config get-value project)
          gcloud builds submit --tag gcr.io/${project_id}/alpine-wheels --timeout 30m
