name: Alpine base image with wheels

on:
  schedule:
    # At 12:00 on Monday (https://crontab.guru/#0_12_*_*_1)
    - cron: '0 12 * * 1'

jobs:

  alpine-with-wheels:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/@master
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      # This pre-builds wheels for xmlsec and grpcio into a base image because they seem to take a long time to compile.
      - name: Build xmlsec and grpcio
        run: |
          cd alpine-wheels
          project_id=$(gcloud config get-value project)
          gcloud builds submit --tag gcr.io/${project_id}/alpine-wheels --timeout 30m
