# This is a basic workflow to create, configure and deploy artefacts and resources
# for the PPE Inventory project in the DEMO environment

name: GCP Deploy

on:
  push:
    branches: [ master ]
    paths: 
    - 'ofsted-client/**'

jobs:

  ofsted-client:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/@master
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      # Deploy the container
      # see: https://cloud.google.com/run/docs/locations
      # NB Cloud Run is currently available in eurompe-west1 (Belgium) and europe-west2 (Netherlands) but not europe-west2 (London)
      - name: Build feed-client image
        run: |
          cd ofsted-client
          project_id=$(gcloud config get-value project)
          gcloud builds submit --tag gcr.io/${project_id}/ofsted-client --timeout 15m
      - name: Deploy feed-client container
        run: |
          project_id=$(gcloud config get-value project)
          project_number=$(gcloud projects describe $project_id --format="value(projectNumber)")
          function_url=https://europe-west2-${project_id}.cloudfunctions.net/proxy
          gcloud run deploy ofsted-client --image=gcr.io/${project_id}/ofsted-client \
            --platform=managed --region=europe-west1 --allow-unauthenticated \
            --update-env-vars=FUNCTION_URL=${function_url},PROJECT_NUMBER=${project_number},WSDL=./wsdl.xml
